#!/usr/bin/env python3
"""Generates the SQL seed and Dart enum from amfi_categories.json.
Used as a fallback when node/tsx is not installed."""
import json, os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.abspath(os.path.join(ROOT, "..", ".."))
JSON_PATH = os.path.join(ROOT, "out", "amfi_categories.json")
SQL_PATH = os.path.join(ROOT, "out", "019_seed_amfi_categories.sql")
DART_PATH = os.path.join(PROJ, "lib", "core", "constants", "amfi_category.g.dart")

cats = json.load(open(JSON_PATH))

def pgquote(s): return "'" + s.replace("'", "''") + "'"
def pgarr(arr):
    parts = ['"' + a.replace('"', '\\"') + '"' for a in arr]
    return "'{" + ",".join(parts) + "}'::text[]"

# ── SQL seed ──────────────────────────────────────────────────────────────
lines = ["-- 019_seed_amfi_categories.sql",
         "-- GENERATED by tools/amfi_scraper/_gen.py -- do not edit by hand.",
         ""]
for c in cats:
    lines.append("INSERT INTO amfi_category (id, super_category, name, sebi_definition, match_patterns, tier1_benchmark, tier2_benchmark, default_term, default_asset_class, default_tax_category)")
    lines.append("VALUES (" + ", ".join([
        pgquote(c['id']), pgquote(c['super_category']), pgquote(c['name']),
        pgquote(c['sebi_definition']), pgarr(c['match_patterns']),
        pgquote(c['tier1_benchmark']), pgquote(c['tier2_benchmark']),
        pgquote(c['default_term']), pgquote(c['default_asset_class']),
        pgquote(c['default_tax_category'])
    ]) + ")")
    lines.append("ON CONFLICT (id) DO UPDATE SET super_category = EXCLUDED.super_category, name = EXCLUDED.name, sebi_definition = EXCLUDED.sebi_definition, match_patterns = EXCLUDED.match_patterns, tier1_benchmark = EXCLUDED.tier1_benchmark, tier2_benchmark = EXCLUDED.tier2_benchmark, default_term = EXCLUDED.default_term, default_asset_class = EXCLUDED.default_asset_class, default_tax_category = EXCLUDED.default_tax_category;")
    lines.append("")
open(SQL_PATH, "w").write("\n".join(lines))
print(f"Wrote {SQL_PATH} ({len(cats)} rows)")

# ── Dart enum ─────────────────────────────────────────────────────────────
def camel(snake):
    parts = snake.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])

def dq(s): return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"

dart = []
dart.append("// GENERATED -- do not edit by hand. Run tools/amfi_scraper/gen_dart.ts (or _gen.py)")
dart.append("")
dart.append("import 'asset_classes.dart';")
dart.append("import '../../data/models/goal_model.dart' show GoalTerm;")
dart.append("")
dart.append("enum AmfiCategory {")
for c in cats:
    dart.append(f"  {camel(c['id'])},")
dart.append("}")
dart.append("")
dart.append("extension AmfiCategoryX on AmfiCategory {")

def add_switch(getter_sig, getter_body):
    dart.append("  " + getter_sig + " {")
    dart.append("    switch (this) {")
    for c in cats:
        dart.append("      case AmfiCategory." + camel(c['id']) + ": return " + getter_body(c) + ";")
    dart.append("    }")
    dart.append("  }")
    dart.append("")

add_switch("String get id", lambda c: dq(c['id']))
add_switch("String get superCategory", lambda c: dq(c['super_category']))
add_switch("String get displayName", lambda c: dq(c['name']))
add_switch("String get tier1Benchmark", lambda c: dq(c['tier1_benchmark']))
add_switch("String get tier2Benchmark", lambda c: dq(c['tier2_benchmark']))
add_switch("GoalTerm get defaultTerm", lambda c: f"GoalTerm.{c['default_term']}")
def asset_class(c):
    v = c['default_asset_class']
    return "AssetClass." + (v[0].lower() + v[1:])
add_switch("AssetClass get defaultAssetClass", asset_class)
add_switch("TaxCategory get defaultTaxCategory", lambda c: f"TaxCategory.{c['default_tax_category']}")

dart.append("  static AmfiCategory? fromId(String id) {")
dart.append("    for (final v in AmfiCategory.values) {")
dart.append("      if (v.id == id) return v;")
dart.append("    }")
dart.append("    return null;")
dart.append("  }")
dart.append("}")
dart.append("")

os.makedirs(os.path.dirname(DART_PATH), exist_ok=True)
open(DART_PATH, "w").write("\n".join(dart))
print(f"Wrote {DART_PATH}")
