// Reads out/amfi_categories.json and writes out/019_seed_amfi_categories.sql
// with one INSERT … ON CONFLICT (id) DO UPDATE per row.
//
// Run: `npx tsx gen_sql.ts`

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "out");

interface Cat {
  id: string;
  super_category: string;
  name: string;
  sebi_definition: string;
  match_patterns: string[];
  tier1_benchmark: string;
  tier2_benchmark: string;
  default_term: string;
  default_asset_class: string;
  default_tax_category: string;
}

function pgQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

function pgArray(arr: string[]): string {
  const escaped = arr.map((a) => '"' + a.replace(/"/g, '\\"') + '"').join(",");
  return "'{" + escaped + "}'::text[]";
}

function main() {
  const cats: Cat[] = JSON.parse(
    readFileSync(join(OUT_DIR, "amfi_categories.json"), "utf8"),
  );
  const lines: string[] = [
    "-- 019_seed_amfi_categories.sql",
    "-- GENERATED by tools/amfi_scraper/gen_sql.ts — do not edit by hand.",
    "",
  ];
  for (const c of cats) {
    lines.push(
      `INSERT INTO amfi_category (id, super_category, name, sebi_definition, match_patterns, tier1_benchmark, tier2_benchmark, default_term, default_asset_class, default_tax_category)`,
    );
    lines.push(
      `VALUES (${pgQuote(c.id)}, ${pgQuote(c.super_category)}, ${pgQuote(c.name)}, ${pgQuote(c.sebi_definition)}, ${pgArray(c.match_patterns)}, ${pgQuote(c.tier1_benchmark)}, ${pgQuote(c.tier2_benchmark)}, ${pgQuote(c.default_term)}, ${pgQuote(c.default_asset_class)}, ${pgQuote(c.default_tax_category)})`,
    );
    lines.push(
      `ON CONFLICT (id) DO UPDATE SET super_category = EXCLUDED.super_category, name = EXCLUDED.name, sebi_definition = EXCLUDED.sebi_definition, match_patterns = EXCLUDED.match_patterns, tier1_benchmark = EXCLUDED.tier1_benchmark, tier2_benchmark = EXCLUDED.tier2_benchmark, default_term = EXCLUDED.default_term, default_asset_class = EXCLUDED.default_asset_class, default_tax_category = EXCLUDED.default_tax_category;`,
    );
    lines.push("");
  }
  writeFileSync(join(OUT_DIR, "019_seed_amfi_categories.sql"), lines.join("\n"));
  console.log(`Wrote ${cats.length} INSERT statements`);
}

main();
